Fix auto-enable arch repos
After enabling arch repos,  need to download database files.  Otherwise, calls to
`pacman -S` return errors that are suppressed by redirection to /dev/null.

Error Message:

```sh
warning: database file for 'extra' does not exist (use "-Sy" to download)
error: failed to prepare transcation (could not find database)
```

Fixes: https://github.com/LukeSmithxyz/LARBS/issues/393